# Don't print a new line at the start of the prompt
add_newline = true
# Pipes ╰─ ╭─
# Powerline symbols                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗

# format = """
# $cmd_duration$username$hostname $directory $git_branch
# $character
# """
format = """
$cmd_duration$directory $git_branch$git_status
$character
"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[• ](bold fg:white) "
error_symbol = "[• 󰅙](bold fg:white) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bg: white"
symbol = "󰘬"
truncation_length = 4
truncation_symbol = ""
format = "• [](bold fg:white)[$symbol $branch(:$remote_branch)](fg:black bg:white)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

#[git_status]
#conflicted = " 🏳 "
#ahead = " 🏎💨 "
#behind = " 😰 "
#diverged = " 😵 "
#untracked = " 🤷 ‍"
#stashed = " 📦 "
#modified = " 📝 "
#staged = '[++\($count\)](green)'
#renamed = " ✍️ "
#deleted = " 🗑 "

[git_status]
format = "[$conflicted](fg:black bg:white)[$untracked](fg:black bg:white)[$modified$renamed](fg:black bg:white)[$staged](fg:black bg:white)[$deleted](fg:black bg:white)[ ](bold fg:white)"
ahead = ' ⇡${count}'
diverged = ' ⇕⇡${ahead_count}⇣${behind_count}'
behind = ' ⇣${count}'
conflicted = " !$count"
untracked = " ?$count"
modified = " ~$count"
deleted = " -$count"
staged = " +$count"
renamed = " »$count"
stashed = " $$count"

[hostname]
ssh_only = false
format =  "[•$hostname](bg:cyan bold fg:black)[](bold fg:cyan )"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:cyan fg:black"
style_root = "red bold"
format = "[](bold fg:cyan)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = "  "
read_only = "  "
style = "bg:white fg:black"
truncation_length = 6
truncation_symbol = "••/"
format = '[](bold fg:white)[$path ]($style)[](bold fg:white)'


[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "

[cmd_duration]
min_time = 0
format = '[](bold fg:white)[ $duration](bold bg:white fg:black)[](bold fg:white) •• '
