exec-once = kwalletd5

#wallpaper
$wallpaper_path=/home/akira/Pictures/wallpaper/swaybg/neko.jpg
exec-once = swaybg -i $wallpaper_path -m fill

#waybar
exec-once = waybar

#fcitx5
exec-once = fcitx5 --replace -d

#network
exec-once = clash
exec-once = NetworkManager
exec-once = nm-applet

exec-once = pw-volume

exec-once = mako

exec-once = /usr/lib/polkit-kde-authentication-agent-1

exec-once = wl-paste --type text cliphist store
exec-once = wl-paste --type image cliphist store

exec-once = linuxqq

