windowrulev2 = nomaximizerequest, class:.* # You'll probably like this.
windowrulev2 = tile,class:^(wps|et|wpp|pdf)$,title:^(WPS文字|WPS表格|WPS演示|WPS PDF)$
windowrulev2 = tile,class:^(vofa+)$
windowrulev2 = tile,class:^(xmind)$
windowrulev2 = tile,class:^(netease-cloud-music)$
